version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.0-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./.docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - '${WEB_SERVER_PORT}:80'
    environment:
      PHP_ENABLE_XDEBUG: 1
    env_file:
      - .env
  database:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: on-failure
    volumes:
      - db:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
volumes:
  db: